### ISSUE TITLE
Link does not open

### ISSUE THREAD

**Issue by CodeLit** [makhnanov/bro-launcher#3]
https://github.com/makhnanov/bro-launcher-build/archive/refs/heads/main.zip

**Comment by CodeLit** [comment]
<img width="632" alt="image" src="https://github.com/makhnanov/bro-launcher/assets/37398131/975664d1-cbdb-4595-8061-bff5bd7aa5d6">

**Comment by makhnanov** [comment]
Thank you. [Fixed.](https://github.com/makhnanov/bro-launcher/releases/tag/v1.9.4)
